version: "3"
services:
  web:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - "php:php"
    volumes:
      - "./web:/var/keebsocial"
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "./web:/var/keebsocial"